default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # Dockerのサービス名 "db" を指定
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>

development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  # テスト用DB名
  database: anta_santa_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>